---
swagger: "2.0"
info:
  description: "A demo API to access and control the Tesla Model S"
  version: "0.0.1"
  title: "Tesla Model S API"
host: "virtserver.swaggerhub.com"
basePath: "/kevincam3/Tesla-ModelS-API/0.0.1"
schemes:
- "https"
paths:
  /vehicle:
    get:
      description: "Details about owned vehicle"
      operationId: "vehicleGET"
      parameters: []
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/inline_response_200"
      x-swagger-router-controller: "Default"
definitions:
  inline_response_200:
    properties:
      color:
        type: "string"
        example: "Red"
      display_name:
        type: "string"
        example: "Kevin's Model S"
      vehicle_id:
        type: "string"
        example: "jajaewfw312"
      vin:
        type: "string"
        example: "kevincame2323"
